# Time Series of Hurricane's Effect on Stream Water Concentrations

Author: [Karolina Sienko](https://github.com/karolinasienko)

Contributors: [Max Czapanskiy](https://github.com/FlukeAndFeather) & [Ale Vida Meza](https://github.com/avidalmeza)

## Background
This repository contains all of the data and code used to analyze the effects of Hurricane Hugo's disturbance on stream water concentrations of potassium, nitrate, magnesium, calcium, and ammonium, in Puente Roto Mameyes (PRM) and Bisley Quebradas 1, 2 and 3 (BQ1, BQ2, BQ3). The purpose is to reproduce Figure 3 from a paper done by Schaefer, Douglas. A. et al. titled *Effects of hurricane disturbance on stream water concentrations and fluxes in eight tropical forest watersheds of the Luquillo Experimental Forest, Puerto Rico*.



## Data
The relevant data for this analysis was downloaded from EDI Data Portal at https://portal.edirepository.org/nis/mapbrowse?packageid=knb-lter-luq.20.4923064. 

The following files were downloaded, and they can be found in the folder `1_raw_data`:

- QuebradaCuenca1-Bisley.csv
- QuebradaCuenca2-Bisley.csv
- QuebradaCuenca3-Bisley.csv
- RioMameyesPuenteRoto.csv


## Methods
```{r}
library(tidyverse)
library(lubridate)

source("../R/moving-average.R")

# Reading in each dataset
bq1_data <- read_csv("../1_raw_data/QuebradaCuenca1-Bisley.csv")
bq2_data <- read_csv("../1_raw_data/QuebradaCuenca2-Bisley.csv")
bq3_data <- read_csv("../1_raw_data/QuebradaCuenca3-Bisley.csv")
PRM_data <- read_csv("../1_raw_data/RioMameyesPuenteRoto.csv")


# Extracting relevant columns (date, concentrations, etc.)
relevant_bq1 <- bq1_data |>
  filter(Sample_Date >= "1988-10-18" & Sample_Date <= "1994-12-31") |>
  select(Sample_ID, Sample_Date, K, `NO3-N`, Mg, Ca, `NH4-N`)

relevant_bq2 <- bq2_data |>
  filter(Sample_Date >= "1988-10-18" & Sample_Date <= "1994-12-31") |>
  select(Sample_ID, Sample_Date, K, `NO3-N`, Mg, Ca, `NH4-N`)

relevant_bq3 <- bq3_data |>
  filter(Sample_Date >= "1988-10-18" & Sample_Date <= "1994-12-31") |>
  select(Sample_ID, Sample_Date, K, `NO3-N`, Mg, Ca, `NH4-N`)

relevant_PRM <- PRM_data |>
  filter(Sample_Date >= "1988-10-18" & Sample_Date <= "1994-12-31") |>
  select(Sample_ID, Sample_Date, K, `NO3-N`, Mg, Ca, `NH4-N`)


# Calling the moving_average function to get the tibble of average conc. for all watersheds
bq1_smoothed <- moving_average(relevant_bq1)
bq2_smoothed <- moving_average(relevant_bq2)
bq3_smoothed <- moving_average(relevant_bq3)
PRM_smoothed <- moving_average(relevant_PRM)


# Combining all smoothed tables
combined_table <- rbind(bq1_smoothed, bq2_smoothed, bq3_smoothed, PRM_smoothed)


# Manipulating the data frame
combined_table_long <- combined_table |>
  pivot_longer(
    cols = "k_mgl":"NH4_ugl",
    names_to = "Nutrient",
    values_to = "Concentration"
  )


# Graphing each watershed's concentrations
combined_table_long |>
  ggplot(
    aes(
      x = window_start,
      y = Concentration,
      linetype = Sample_ID
    )
  ) +
  geom_line() +
  theme(
    strip.placement = "outside"
  ) +
  geom_vline(
    xintercept = date("1989-09-19"),
    linetype = "dashed"
  ) +
  labs(
    title = "Nutrient Concentrations with 9-week Moving Average",
    y = "Concentration",
    x = "Years"
  ) +
  facet_grid(Nutrient ~ ., scales = "free", switch = "y")

```

## Results


